### ISSUE TITLE
Flash of unstyled content

### ISSUE THREAD

**Issue by gosoccerboy5** [gosoccerboy5/gosoccerboy5.github.io#1]
go to [the 404 page](//gosoccerboy5.github.io/404) and when it loads, there's a quick flash of unstyled content. this is probably because I'm loading stylesheets and adding some html programmatically with JS. is there any way to fix this, or should I load the stylesheet individually instead of through JS?

**Comment by FunctionalMetatable** [comment]
plz use jekyll

**Comment by gosoccerboy5** [comment]
> plz use jekyll

no thanks i wanna build my own site

**Comment by FunctionalMetatable** [comment]
> > plz use jekyll
> 
> no thanks i wanna build my own site

then you have to do it individually instead of injecting it in via js

**Comment by gosoccerboy5** [comment]
> > > plz use jekyll
> > 
> > 
> > no thanks i wanna build my own site
> 
> then you have to do it individually instead of injecting it in via js
> 
> or put the script src bit in the top of the page (head el)

I might try that thanks

**Comment by gosoccerboy5** [comment]
I could solve this by individually adding the stylesheet to each page. Too laze tho
