### ISSUE TITLE
Somewhy

### ISSUE THREAD

**Issue by Quantum-Codes** [gosoccerboy5/gosoccerboy5.github.io#32]
It exists and not..,
https://en.m.wiktionary.org/wiki/somewhy#:~:text=some%20%2B%E2%80%8E%20why.-,Adverb,For%20some%20reason%20quotations%20%E2%96%BC   

You have such a good vocabulary (not sarcastic... it's there in websites!!!)

**Comment by gosoccerboy5** [comment]
ok
